// Handler voice lines: ElevenLabs text-to-speech clips in assets/audio/voice/<key>.mp3, played through a radio
// filter with a subtitle. A missing clip still shows its subtitle. `pri`: a higher-priority line interrupts a lower
// one; equal or lower ones queue (or drop when the queue is full). `cd`: minimum seconds between plays of this key.
export const VOICE_LINES = {
  start: { text: "Operator, you're jacked in. Build along the streets, then call the first wave.", pri: 1 },
  wave_start_1: { text: 'Hostiles inbound.', pri: 0, cd: 20 },
  wave_start_2: { text: 'Contacts on the grid. Here they come.', pri: 0, cd: 20 },
  wave_start_3: { text: 'Next wave is moving. Stay sharp.', pri: 0, cd: 20 },
  wave_clear_1: { text: 'Wave neutralized.', pri: 0, cd: 20 },
  wave_clear_2: { text: "Grid's clear. Spend those credits.", pri: 0, cd: 20 },
  core_critical: { text: "Core integrity critical! Don't let anything else through!", pri: 3, cd: 30 },
  victory: { text: 'District secured. Nice work, operator.', pri: 4 },
  defeat: { text: "The core's breached. We've lost the district.", pri: 4 },
  endless: { text: "Endless mode. The corps won't stop sending them. Neither will we.", pri: 2 },
  boss_titan: { text: 'Titan Warframe on the grid. Heavy armor. Railguns and orbital strikes, now.', pri: 3 },
  boss_overmind: { text: "That's the Overmind. Rogue AI core. Break its shield, then take the hull apart.", pri: 3 },
  phase_titan: { text: "It's venting an EMP pulse. Towers near the Titan are down!", pri: 2, cd: 8 },
  phase_overmind: { text: 'The Overmind is hijacking our towers!', pri: 2, cd: 8 },
  threat_runner: { text: "Street runners. Chromed-up punks. Nothing a pulse laser can't handle.", pri: 1 },
  threat_drone: { text: "Hunter drones, airborne. Mortars can't touch them.", pri: 1 },
  threat_brute: { text: 'Heavy mechs. That armor shrugs off small hits. Railguns cut straight through.', pri: 1 },
  threat_aegis: { text: 'Aegis units. Their shields regenerate. Tesla coils eat shields for breakfast.', pri: 1 },
  threat_phantom: { text: "Phantoms. Full optical camo. You'll need detection, or an uplink field.", pri: 1 },
  threat_splitter: { text: 'Replicators. Kill one and it bursts into nano-mites.', pri: 1 },
  threat_medic: { text: 'Patch drones. They repair everything around them. Take them out first.', pri: 1 },
  threat_jammer: { text: 'Signal jammers. Any tower in their field goes dark. Out-range them, or firewall your towers.', pri: 1 },
  threat_courier: { text: "Data couriers. They'll grab a packet from the core and run for the exit. Don't let them out.", pri: 1 },
  data_stolen: { text: "They've got a data packet! Stop that courier before it gets out!", pri: 2, cd: 12 },
  data_escaped: { text: "Packet's gone. That one's going to hurt.", pri: 2, cd: 10 },
  data_recovered: { text: 'Packet recovered.', pri: 1, cd: 10 },
  jammed: { text: 'Our towers are being jammed!', pri: 1, cd: 45 },
  variant_mirror: { text: 'Mirror plating on those units. Lasers will glance right off.', pri: 1 },
  variant_insulated: { text: "Insulated hulls. Tesla arcs won't chain through them.", pri: 1 },
  variant_thermal: { text: "Heat-sinked units. Cryo and fire won't stick to them.", pri: 1 },
  mutators: { text: 'Heads up. This wave is running modified hardware.', pri: 1, cd: 30 },
};
